### ISSUE TITLE
How to get started using the product?

### ISSUE THREAD

**Issue by ahmedhamodi** [decisionhub/decisionhub.github.io#21]
Need to make it clear or automate the signup process (with payment)

**Comment by GodGreg** [comment]
> Need to make it clear or automate the signup process (with payment)

@ahmedhamodi What if we just add our emails as a temporary solution. And we can handle it from there.

**Comment by ahmedhamodi** [comment]
> @ahmedhamodi What if we just add our emails as a temporary solution. And we can handle it from there.

Sure, we can add our support email. It's already there but I'll make it a bit more clear
